### ISSUE TITLE
[Test Configuration] Windows Perf counter of work item level doesn't support wildcards

### ISSUE THREAD

**Issue by Live2Learn** [merione/public#151]
`<WindowsPerfCounters>
          <PerfCounter name='\Network Interface(*)\Current Bandwidth' type='Average' intervalInMinute='1' workItemAggregate='Average' taskAggregate='None' takeSampleWhenStop='true'/>
</WindowsPerfCounters>
`

The \* won't be expanded. And Meri says

`Unexpected Exception when new PerformanceCounter object: System.InvalidOperationException: Instance '*' does not exist in the specified Category.
   at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at Meri.SDK.PerfCounter.Aggregator.WindowsPCAggregator..ctor(String categoryName, String counterName, String instanceName) in`

**Comment by Live2Learn** [comment]
We can wrapper this method in .Net [msdn link](http://msdn.microsoft.com/en-us/library/windows/desktop/aa372606%28v=vs.85%29.aspx)
