### ISSUE TITLE
Meri SDK version may incorrect after upgrade (check the copy meri assembly part when initializing)

### ISSUE THREAD

**Issue by gildorwang** [merione/public#35]
<a href="https://github.com/RodgeFu"><img src="https://avatars.githubusercontent.com/u/6038235?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RodgeFu](https://github.com/RodgeFu)**
_Saturday Jan 18, 2014 at 03:44 GMT_
_Originally opened as https://github.com/gildorwang/meri2/issues/164_

---

  [2014-01-17T19:26:02.6928083Z]    Exception caught when creating AppDomain, WorkItemRunInfoId=f5de5941-4fce-4558-922e-0374b1d4c5ec, Message=System.Exception: Exception from remoteAgent: System.TypeLoadException: Could not load type 'Meri.SDK.PerfCounter.Aggregator.FakePCAggregator' from assembly 'Meri.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at Meri.Utilities.Helpers.AssemblyHelper.CreateInstance(String assembly, String type) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Utilities\Helpers\AssemblyHelper.cs:line 77
   at Meri.SDK.PerfCounter.MeriPerfCounterManager.CreatePerfCounterIfNotExist(PerfCounterDefinition perfCounterDefinition) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\SDK\PerfCounter\MeriPerfCounterManager.cs:line 51
   at Meri.Engine.WorkItemRunDriverRemoteAgent.InitializePerfCounter() in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemRunDriverRemoteAgent.cs:line 294
   at Meri.Engine.WorkItemRunDriverRemoteAgent.Initialize(WorkItemRunDriverRemoteAgentContext agentContext) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemRunDriverRemoteAgent.cs:line 169

Server stack trace: 
   at Meri.Engine.WorkItemRunDriverRemoteAgent.Initialize(WorkItemRunDriverRemoteAgentContext agentContext) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemRunDriverRemoteAgent.cs:line 177
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Meri.Engine.WorkItemRunDriverRemoteAgent.Initialize(WorkItemRunDriverRemoteAgentContext agentContext)
   at Meri.Engine.WorkItemAppDomain.CreateWorkItemDomain(WorkItemRunDriverRemoteAgentContext agentContext, WorkItemRunDriverEventProxy eventProxy) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemAppDomain.cs:line 52
[Meri][f5de5941-4fce-4558-922e-0374b1d4c5ec_Driver][Information][WorkerRole_IN_5][241][{null}]
  [2014-01-17T19:26:02.7396832Z]    Finish Create Domain for WorkItemRun f5de5941-4fce-4558-922e-0374b1d4c5ec
[Meri][f5de5941-4fce-4558-922e-0374b1d4c5ec_Driver][Error][WorkerRole_IN_5][241][{null}]
  [2014-01-17T19:26:02.7396832Z]    Unexpected error when starting WorkItemRunDriver, runId = f5de5941-4fce-4558-922e-0374b1d4c5ec
 Exception = System.Exception: Exception from remoteAgent: System.TypeLoadException: Could not load type 'Meri.SDK.PerfCounter.Aggregator.FakePCAggregator' from assembly 'Meri.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at Meri.Utilities.Helpers.AssemblyHelper.CreateInstance(String assembly, String type) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Utilities\Helpers\AssemblyHelper.cs:line 77
   at Meri.SDK.PerfCounter.MeriPerfCounterManager.CreatePerfCounterIfNotExist(PerfCounterDefinition perfCounterDefinition) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\SDK\PerfCounter\MeriPerfCounterManager.cs:line 51
   at Meri.Engine.WorkItemRunDriverRemoteAgent.InitializePerfCounter() in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemRunDriverRemoteAgent.cs:line 294
   at Meri.Engine.WorkItemRunDriverRemoteAgent.Initialize(WorkItemRunDriverRemoteAgentContext agentContext) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemRunDriverRemoteAgent.cs:line 169

Server stack trace: 
   at Meri.Engine.WorkItemRunDriverRemoteAgent.Initialize(WorkItemRunDriverRemoteAgentContext agentContext) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemRunDriverRemoteAgent.cs:line 177
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Meri.Engine.WorkItemRunDriverRemoteAgent.Initialize(WorkItemRunDriverRemoteAgentContext agentContext)
   at Meri.Engine.WorkItemAppDomain.CreateWorkItemDomain(WorkItemRunDriverRemoteAgentContext agentContext, WorkItemRunDriverEventProxy eventProxy) in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemAppDomain.cs:line 73
   at Meri.Engine.WorkItemRunDriver.InnerStart() in c:\tfs\meri_codebox\Meri-dev\Src\Svc\Engine\WorkItemRunDriver.cs:line 155

**Comment by gildorwang** [comment]
<a href="https://github.com/gildorwang"><img src="https://avatars.githubusercontent.com/u/1061388?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gildorwang](https://github.com/gildorwang)**
_Saturday Jan 18, 2014 at 13:01 GMT_

---

I created a new label 'SDK' for it :smile:

**Comment by RodgeFu** [comment]
No repro
